name: make_docs
on:
  push:
    branches:
      - main
jobs:
  make-docs:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - run: uv sync --group docs
      - run: uv run mkdocs gh-deploy --force --clean
