name: make_docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "src/saa/clock.py"
      - ".github/workflows/docs.yaml"
jobs:
  make-docs:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: "3.12"

      - run: uv sync --group docs
      - run: uv run mkdocs gh-deploy --force --clean
