name: qa_test
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v3
      - run: rye pin 3.12.2         # pin your Python version
      - run: |                    # abort if the lockfile changes
          rye sync
      - run: rye fmt --check      # check formatting is correct
      - run: rye lint             # and linting
      - run: rye run check        # typecheck too
      - run: rye run test         # then run your tests!
